# Generated by Django 3.0.1 on 2020-02-14 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_auto_20200117_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='num_processes',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='ping',
            name='process_id',
            field=models.IntegerField(default=0),
        ),
    ]
